--- #YAML:1.0
name:               Vimana
version:            0.01
abstract:           The great new Vimana!
author:
    - Cornelius <cornelius@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    App::CLI:             0.08
    Archive::Any:         0
    Cache::File:          0
    Class::Accessor::Fast:  0
    File::Copy::Recursive:  0
    File::Find::Rule:     0
    File::Path:           0
    File::Spec:           0
    File::Temp:           0
    File::Type:           0
    Getopt::Long:         0
    LWP::UserAgent:       0
    Test::More:           0
    URI:                  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
