---
abstract: 'Vim script port manager'
author:
  - 'You-An Lin <cornelius.howl@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.92
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Vimana
no_index:
  directory:
    - inc
    - t
    - xt
provides:
  Vimana:
    file: lib/Vimana.pm
    version: 2.21
  Vimana::Archive:
    file: lib/Vimana/Archive.pm
  Vimana::Command:
    file: lib/Vimana/Command.pm
  Vimana::Command::Download:
    file: lib/Vimana/Command/Download.pm
  Vimana::Command::Help:
    file: lib/Vimana/Command/Help.pm
  Vimana::Command::Info:
    file: lib/Vimana/Command/Info.pm
  Vimana::Command::Install:
    file: lib/Vimana/Command/Install.pm
  Vimana::Command::Installed:
    file: lib/Vimana/Command/Installed.pm
  Vimana::Command::Rate:
    file: lib/Vimana/Command/Rate.pm
  Vimana::Command::Remove:
    file: lib/Vimana/Command/Remove.pm
  Vimana::Command::Search:
    file: lib/Vimana/Command/Search.pm
  Vimana::Command::Update:
    file: lib/Vimana/Command/Update.pm
  Vimana::Command::Upgrade:
    file: lib/Vimana/Command/Upgrade.pm
  Vimana::GitInstall:
    file: lib/Vimana/GitInstall.pm
  Vimana::Index:
    file: lib/Vimana/Index.pm
  Vimana::Installer:
    file: lib/Vimana/Installer.pm
  Vimana::Installer::Auto:
    file: lib/Vimana/Installer/Auto.pm
  Vimana::Installer::Makefile:
    file: lib/Vimana/Installer/Makefile.pm
  Vimana::Installer::Meta:
    file: lib/Vimana/Installer/Meta.pm
  Vimana::Installer::Rakefile:
    file: lib/Vimana/Installer/Rakefile.pm
  Vimana::Installer::Text:
    file: lib/Vimana/Installer/Text.pm
  Vimana::Installer::Vimball:
    file: lib/Vimana/Installer/Vimball.pm
  Vimana::Logger:
    file: lib/Vimana/Logger.pm
  Vimana::Logger::Compat:
    file: lib/Vimana/Logger.pm
  Vimana::Record:
    file: lib/Vimana/Record.pm
  Vimana::Recursive:
    file: lib/Vimana/Recursive.pm
    version: 0.38
  Vimana::Util:
    file: lib/Vimana/Util.pm
  Vimana::VimOnline:
    file: lib/Vimana/VimOnline.pm
  Vimana::VimOnline::ScriptPage:
    file: lib/Vimana/VimOnline/ScriptPage.pm
  Vimana::VimOnline::Search:
    file: lib/Vimana/VimOnline/Search.pm
requires:
  App::CLI: 0.08
  Archive::Extract: 0
  DateTime: 0
  Digest::MD5: 0
  Exporter::Lite: 0
  File::Path: 2.07
  File::Spec: 0
  File::Temp: 0
  File::Type: 0
  Getopt::Long: 0
  HTTP::Lite: 0
  JSON::PP: 0
  LWP::Simple: 0
  LWP::UserAgent: 0
  Mouse: 0
  Regexp::Common: 0
  URI: 1.37
  Web::Scraper: 0
  YAML: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/c9s/Vimana
version: 2.21
